CREATE TABLE IF NOT EXISTS units (
 "id" integer not null primary key,
 "resource_manager" text default "", 
 "cluster_id" text,
 "uuid" text,
 "name" text,
 "project" text,
 "groupname" text,
 "username" text,
 "created_at" text,
 "started_at" text,
 "ended_at" text,
 "created_at_ts" integer,
 "started_at_ts" integer,
 "ended_at_ts" integer,
 "elapsed" text,
 "state" text,
 "allocation" text default '{}',
 "tags" text default '{}',
 "total_time_seconds" text default '{}', 
 "avg_cpu_usage" text default '{}', 
 "avg_cpu_mem_usage" text default '{}',
 "total_cpu_energy_usage_kwh" text default '{}', 
 "total_cpu_emissions_gms" text default '{}', 
 "avg_gpu_usage" text default '{}', 
 "avg_gpu_mem_usage" text default '{}', 
 "total_gpu_energy_usage_kwh" text default '{}', 
 "total_gpu_emissions_gms" text default '{}',
 "total_io_write_stats" text default '{}', 
 "total_io_read_stats" text default '{}', 
 "total_ingress_stats" text default '{}',
 "total_outgress_stats" text default '{}',
 "ignore" integer, 
 "num_updates" integer default 0, 
 "last_updated_at" text
);
CREATE INDEX idx_cluster_id_usr_uuid ON units (cluster_id,username,uuid);
CREATE UNIQUE INDEX uq_cluster_id_uuid_start ON units (cluster_id,uuid,started_at);
