DROP INDEX IF EXISTS uq_uuid_start;
DROP INDEX IF EXISTS idx_usr_uuid;
DROP INDEX IF EXISTS idx_usr_project_start;
ALTER TABLE usage DROP COLUMN "num_updates";
ALTER TABLE units DROP COLUMN "num_updates";
ALTER TABLE units RENAME COLUMN ended_at_ts to end_ts;
ALTER TABLE units RENAME COLUMN started_at_ts to start_ts;
ALTER TABLE units RENAME COLUMN created_at_ts to submit_ts;
ALTER TABLE units RENAME COLUMN ended_at to 'end';
ALTER TABLE units RENAME COLUMN started_at to 'start';
ALTER TABLE units RENAME COLUMN created_at to submit;
ALTER TABLE units ADD COLUMN "exitcode" text;
UPDATE units SET exitcode = json_extract(tags, '$.exit_code');
UPDATE units SET tags = json_remove(tags, '$.exit_code');
CREATE INDEX IF NOT EXISTS idx_usr_project_start ON units (usr,project,start);
CREATE INDEX IF NOT EXISTS idx_usr_uuid ON units (usr,uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uq_uuid_start ON units (uuid,start);
