CREATE TABLE IF NOT EXISTS units (
 "id" integer not null primary key,
 "uuid" text,
 "name" text,
 "project" text,
 "grp" text,
 "usr" text,
 "submit" text,
 "start" text,
 "end" text,
 "submit_ts" integer,
 "start_ts" integer,
 "end_ts" integer,
 "elapsed" text,
 "elapsed_raw" integer,
 "exitcode" text,
 "state" text,
 "allocation" text default '{}',
 "total_cpu_billing" integer,
 "total_gpu_billing" integer,
 "total_misc_billing" integer,
 "avg_cpu_usage" real,
 "avg_cpu_mem_usage" real,
 "total_cpu_energy_usage_kwh" real,
 "total_cpu_emissions_gms" real,
 "avg_gpu_usage" real,
 "avg_gpu_mem_usage" real,
 "total_gpu_energy_usage_kwh" real,
 "total_gpu_emissions_gms" real,
 "total_io_write_hot_gb" real,
 "total_io_read_hot_gb" real,
 "total_io_write_cold_gb" real,
 "total_io_read_cold_gb" real,
 "total_ingress_in_gb" real,
 "total_outgress_in_gb" real,
 "tags" text default '{}',
 "ignore" integer
);
CREATE INDEX IF NOT EXISTS idx_usr_project_start ON units (usr,project,start);
CREATE INDEX IF NOT EXISTS idx_usr_uuid ON units (usr,uuid);
CREATE UNIQUE INDEX IF NOT EXISTS uq_uuid_start ON units (uuid,start);
