ALTER TABLE units DROP COLUMN "total_outgress_stats";
ALTER TABLE units DROP COLUMN "total_ingress_stats";
ALTER TABLE units DROP COLUMN "total_io_read_stats";
ALTER TABLE units DROP COLUMN "total_io_write_stats";
ALTER TABLE units DROP COLUMN "total_gpu_emissions_gms";
ALTER TABLE units DROP COLUMN "total_gpu_energy_usage_kwh";
ALTER TABLE units DROP COLUMN "avg_gpu_mem_usage";
ALTER TABLE units DROP COLUMN "avg_gpu_usage";
ALTER TABLE units DROP COLUMN "total_cpu_emissions_gms";
ALTER TABLE units DROP COLUMN "total_cpu_energy_usage_kwh";
ALTER TABLE units DROP COLUMN "avg_cpu_mem_usage";
ALTER TABLE units DROP COLUMN "avg_cpu_usage";
ALTER TABLE units DROP COLUMN "total_time_seconds";

ALTER TABLE usage DROP COLUMN "total_outgress_stats";
ALTER TABLE usage DROP COLUMN "total_ingress_stats";
ALTER TABLE usage DROP COLUMN "total_io_read_stats";
ALTER TABLE usage DROP COLUMN "total_io_write_stats";
ALTER TABLE usage DROP COLUMN "total_gpu_emissions_gms";
ALTER TABLE usage DROP COLUMN "total_gpu_energy_usage_kwh";
ALTER TABLE usage DROP COLUMN "avg_gpu_mem_usage";
ALTER TABLE usage DROP COLUMN "avg_gpu_usage";
ALTER TABLE usage DROP COLUMN "total_cpu_emissions_gms";
ALTER TABLE usage DROP COLUMN "total_cpu_energy_usage_kwh";
ALTER TABLE usage DROP COLUMN "avg_cpu_mem_usage";
ALTER TABLE usage DROP COLUMN "avg_cpu_usage";
ALTER TABLE usage DROP COLUMN "total_time_seconds";

ALTER TABLE units ADD COLUMN "total_walltime_seconds" real;
ALTER TABLE units ADD COLUMN "total_cputime_seconds" real;
ALTER TABLE units ADD COLUMN "total_cpumemtime_seconds" real;
ALTER TABLE units ADD COLUMN "total_gputime_seconds" real;
ALTER TABLE units ADD COLUMN "total_gpumemtime_seconds" real;
ALTER TABLE units ADD COLUMN "avg_cpu_usage" real;
ALTER TABLE units ADD COLUMN "avg_cpu_mem_usage" real;
ALTER TABLE units ADD COLUMN "total_cpu_energy_usage_kwh" real;
ALTER TABLE units ADD COLUMN "total_cpu_emissions_gms" real;
ALTER TABLE units ADD COLUMN "avg_gpu_usage" real;
ALTER TABLE units ADD COLUMN "avg_gpu_mem_usage" real;
ALTER TABLE units ADD COLUMN "total_gpu_energy_usage_kwh" real;
ALTER TABLE units ADD COLUMN "total_gpu_emissions_gms" real;
ALTER TABLE units ADD COLUMN "total_io_write_hot_gb" real;
ALTER TABLE units ADD COLUMN "total_io_read_hot_gb" real;
ALTER TABLE units ADD COLUMN "total_io_write_cold_gb" real;
ALTER TABLE units ADD COLUMN "total_io_read_cold_gb" real;
ALTER TABLE units ADD COLUMN "total_ingress_in_gb" real;
ALTER TABLE units ADD COLUMN "total_outgress_in_gb" real;

ALTER TABLE usage ADD COLUMN "total_walltime_seconds" real;
ALTER TABLE usage ADD COLUMN "total_cputime_seconds" real;
ALTER TABLE usage ADD COLUMN "total_cpumemtime_seconds" real;
ALTER TABLE usage ADD COLUMN "total_gputime_seconds" real;
ALTER TABLE usage ADD COLUMN "total_gpumemtime_seconds" real;
ALTER TABLE usage ADD COLUMN "avg_cpu_usage" real;
ALTER TABLE usage ADD COLUMN "avg_cpu_mem_usage" real;
ALTER TABLE usage ADD COLUMN "total_cpu_energy_usage_kwh" real;
ALTER TABLE usage ADD COLUMN "total_cpu_emissions_gms" real;
ALTER TABLE usage ADD COLUMN "avg_gpu_usage" real;
ALTER TABLE usage ADD COLUMN "avg_gpu_mem_usage" real;
ALTER TABLE usage ADD COLUMN "total_gpu_energy_usage_kwh" real;
ALTER TABLE usage ADD COLUMN "total_gpu_emissions_gms" real;
ALTER TABLE usage ADD COLUMN "total_io_write_hot_gb" real;
ALTER TABLE usage ADD COLUMN "total_io_read_hot_gb" real;
ALTER TABLE usage ADD COLUMN "total_io_write_cold_gb" real;
ALTER TABLE usage ADD COLUMN "total_io_read_cold_gb" real;
ALTER TABLE usage ADD COLUMN "total_ingress_in_gb" real;
ALTER TABLE usage ADD COLUMN "total_outgress_in_gb" real;
