ALTER TABLE usage DROP COLUMN "total_io_write_hot_gb";
ALTER TABLE usage DROP COLUMN "total_io_read_hot_gb";
ALTER TABLE usage DROP COLUMN "total_io_write_cold_gb";
ALTER TABLE usage DROP COLUMN "total_io_read_cold_gb";
ALTER TABLE usage DROP COLUMN "total_ingress_in_gb";
ALTER TABLE usage DROP COLUMN "total_outgress_in_gb";
ALTER TABLE usage DROP COLUMN "total_gpu_emissions_gms";
ALTER TABLE usage DROP COLUMN "total_gpu_energy_usage_kwh";
ALTER TABLE usage DROP COLUMN "avg_gpu_mem_usage";
ALTER TABLE usage DROP COLUMN "avg_gpu_usage";
ALTER TABLE usage DROP COLUMN "total_cpu_emissions_gms";
ALTER TABLE usage DROP COLUMN "total_cpu_energy_usage_kwh";
ALTER TABLE usage DROP COLUMN "avg_cpu_mem_usage";
ALTER TABLE usage DROP COLUMN "avg_cpu_usage";
ALTER TABLE usage DROP COLUMN "total_misctime_seconds";
ALTER TABLE usage DROP COLUMN "total_gpumemtime_seconds";
ALTER TABLE usage DROP COLUMN "total_cpumemtime_seconds";
ALTER TABLE usage DROP COLUMN "total_gputime_seconds";
ALTER TABLE usage DROP COLUMN "total_cputime_seconds";
ALTER TABLE usage DROP COLUMN "total_walltime_seconds";

ALTER TABLE units DROP COLUMN "total_io_write_hot_gb";
ALTER TABLE units DROP COLUMN "total_io_read_hot_gb";
ALTER TABLE units DROP COLUMN "total_io_write_cold_gb";
ALTER TABLE units DROP COLUMN "total_io_read_cold_gb";
ALTER TABLE units DROP COLUMN "total_ingress_in_gb";
ALTER TABLE units DROP COLUMN "total_outgress_in_gb";
ALTER TABLE units DROP COLUMN "total_gpu_emissions_gms";
ALTER TABLE units DROP COLUMN "total_gpu_energy_usage_kwh";
ALTER TABLE units DROP COLUMN "avg_gpu_mem_usage";
ALTER TABLE units DROP COLUMN "avg_gpu_usage";
ALTER TABLE units DROP COLUMN "total_cpu_emissions_gms";
ALTER TABLE units DROP COLUMN "total_cpu_energy_usage_kwh";
ALTER TABLE units DROP COLUMN "avg_cpu_mem_usage";
ALTER TABLE units DROP COLUMN "avg_cpu_usage";
ALTER TABLE units DROP COLUMN "total_misctime_seconds";
ALTER TABLE units DROP COLUMN "total_gpumemtime_seconds";
ALTER TABLE units DROP COLUMN "total_cpumemtime_seconds";
ALTER TABLE units DROP COLUMN "total_gputime_seconds";
ALTER TABLE units DROP COLUMN "total_cputime_seconds";
ALTER TABLE units DROP COLUMN "total_walltime_seconds";

ALTER TABLE usage ADD COLUMN "total_time_seconds" text default '{}';
ALTER TABLE usage ADD COLUMN "avg_cpu_usage" text default '{}';
ALTER TABLE usage ADD COLUMN "avg_cpu_mem_usage" text default '{}';
ALTER TABLE usage ADD COLUMN "total_cpu_energy_usage_kwh" text default '{}';
ALTER TABLE usage ADD COLUMN "total_cpu_emissions_gms" text default '{}';
ALTER TABLE usage ADD COLUMN "avg_gpu_usage" text default '{}';
ALTER TABLE usage ADD COLUMN "avg_gpu_mem_usage" text default '{}';
ALTER TABLE usage ADD COLUMN "total_gpu_energy_usage_kwh" text default '{}';
ALTER TABLE usage ADD COLUMN "total_gpu_emissions_gms" text default '{}';
ALTER TABLE usage ADD COLUMN "total_io_write_stats" text default '{}';
ALTER TABLE usage ADD COLUMN "total_io_read_stats" text default '{}';
ALTER TABLE usage ADD COLUMN "total_ingress_stats" text default '{}';
ALTER TABLE usage ADD COLUMN "total_outgress_stats" text default '{}';

ALTER TABLE units ADD COLUMN "total_time_seconds" text default '{}';
ALTER TABLE units ADD COLUMN "avg_cpu_usage" text default '{}';
ALTER TABLE units ADD COLUMN "avg_cpu_mem_usage" text default '{}';
ALTER TABLE units ADD COLUMN "total_cpu_energy_usage_kwh" text default '{}';
ALTER TABLE units ADD COLUMN "total_cpu_emissions_gms" text default '{}';
ALTER TABLE units ADD COLUMN "avg_gpu_usage" text default '{}';
ALTER TABLE units ADD COLUMN "avg_gpu_mem_usage" text default '{}';
ALTER TABLE units ADD COLUMN "total_gpu_energy_usage_kwh" text default '{}';
ALTER TABLE units ADD COLUMN "total_gpu_emissions_gms" text default '{}';
ALTER TABLE units ADD COLUMN "total_io_write_stats" text default '{}';
ALTER TABLE units ADD COLUMN "total_io_read_stats" text default '{}';
ALTER TABLE units ADD COLUMN "total_ingress_stats" text default '{}';
ALTER TABLE units ADD COLUMN "total_outgress_stats" text default '{}';
