import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from "./docs/api/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

function capitalize(s) {
    return s && String(s[0]).toUpperCase() + String(s).slice(1);
}

// Modify the labels to capitalize the first letter for better UI
for (var i = 0; i < apiSidebar.length; i++) {
  if (apiSidebar[i].label) {
    apiSidebar[i].label = capitalize(apiSidebar[i].label);
  }
}

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ceemsSidebar: [{type: 'autogenerated', dirName: '.'}],
  ceemsApiSidebar: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "CEEMS API",
        description:
          "This is a sample CEEMS API server. For this sample, there is no need to provide basic authentication credentials to test API resources.",
        // slug: "/category/ceems-api",
      },
      items: apiSidebar,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
